# Generated by Django 4.1.7 on 2023-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
