version: "3.9"
services:
  web:
    build: backend
    ports:
      - "8000:8000"
    command: uvicorn core.asgi:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: