# Generated by Django 4.1.7 on 2023-03-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='shortcode',
            field=models.CharField(default='CA', max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flinks.country')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
