# Generated by Django 4.1.7 on 2023-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flinks', '0002_alter_country_options_country_shortcode_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='url',
            field=models.CharField(max_length=355),
        ),
    ]
